apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: llm-chatbot
  title: LLM Chatbot
  description: Creates an LLM-based chatbot using Groq and Streamlit.
  tags:
    - llm
    - chatbot
    - python
    - groq
    - streamlit
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Basic Service Information
      required:
        - component_id
        - owner
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:field: EntityNamePicker
        description:
          type: string
          title: Description
          description: A description for the component.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
              - User

    - title: Configuration
      required:
        - groqApiKey
      properties:
        groqApiKey:
          title: Groq API Key
          type: string
          description: Your API key for the Groq service.
          ui:field: Secret

    - title: Repository Information
      required:
        - repoUrl
      properties:
        repoUrl:
          type: string
          title: Repository URL
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          repoUrl: ${{ parameters.repoUrl }}
          groqApiKey: ${{ parameters.groqApiKey }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: 'This is ${{ parameters.description }}'
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
