apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ${{ parseRepoUrl(values.repoUrl).owner }}/${{ parseRepoUrl(values.repoUrl).repo }}
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
